import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#e8eaef" },
  content: { padding: 24, paddingBottom: 32, flexGrow: 1, justifyContent: "center" },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 22,
    shadowColor: "#0f172a",
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 14,
    elevation: 6,
  },
  hero: { alignItems: "center", marginBottom: 18 },
  logoWrap: {
    height: 70,
    width: 70,
    borderRadius: 20,
    backgroundColor: "#e5f0ff",
    alignItems: "center",
    justifyContent: "center",
  },
  logo: { height: 40, width: 40, resizeMode: "contain" },
  title: { fontSize: 24, fontWeight: "800", color: "#1f2a44", marginTop: 12 },
  subtitle: { marginTop: 6, fontSize: 14, color: "#6b768a", textAlign: "center", lineHeight: 20 },
  form: { marginTop: 10 },
  label: { fontSize: 13, color: "#1f2a44", fontWeight: "600", marginBottom: 6, marginTop: 12 },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#d4dae2",
    borderRadius: 12,
    paddingHorizontal: 14,
    backgroundColor: "#f7f9fc",
    height: 48,
    gap: 10,
  },
  input: { flex: 1, fontSize: 14, color: "#1f2a44" },
  linkRow: { alignItems: "flex-end", marginTop: 8 },
  linkText: { fontSize: 13, color: "#1e6ee8", fontWeight: "600" },
  errorText: { marginTop: 10, color: "#c53030", fontSize: 13 },
  primaryButton: {
    marginTop: 18,
    backgroundColor: "#1d7dec",
    borderRadius: 12,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    shadowColor: "#1d7dec",
    shadowOpacity: 0.35,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 12,
    elevation: 4,
  },
  primaryButtonText: { color: "#ffffff", fontSize: 16, fontWeight: "700" },
  dividerRow: { flexDirection: "row", alignItems: "center", marginTop: 20, gap: 8 },
  divider: { flex: 1, height: 1, backgroundColor: "#e0e5ed" },
  dividerText: { fontSize: 12, color: "#6b768a", fontWeight: "600" },
  socialRow: { flexDirection: "row", marginTop: 14, gap: 12 },
  socialButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#e0e5ed",
    borderRadius: 10,
    height: 48,
    backgroundColor: "#ffffff",
  },
  socialText: { fontSize: 14, color: "#1f2a44", fontWeight: "700" },
  footer: { flexDirection: "row", justifyContent: "center", alignItems: "center", marginTop: 18, gap: 6 },
  footerText: { fontSize: 13, color: "#4b5563" },
  signUpText: { fontSize: 13, color: "#1d7dec", fontWeight: "700" },
});
